"""tirando descricao e local

Revision ID: 07bce8c14651
Revises: 5df60544aea1
Create Date: 2024-05-27 13:06:13.425627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07bce8c14651'
down_revision = '5df60544aea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('descricao')
        batch_op.drop_column('localizacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('localizacao', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
