"""empty message

Revision ID: 35bc032e8356
Revises: 
Create Date: 2024-04-26 23:09:50.487667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35bc032e8356'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_evento', sa.String(length=120), nullable=False),
    sa.Column('data_evento', sa.DateTime(), nullable=False),
    sa.Column('localizacao', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('foto_capa', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('caminho_selfie', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('caminho_foto', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fotos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fotos_timestamp'), ['timestamp'], unique=False)

    op.create_table('imagens_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('caminho_imagem', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imagens_evento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imagens_evento_timestamp'), ['timestamp'], unique=False)

    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('foto_id', sa.Integer(), nullable=True),
    sa.Column('data_compra', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['foto_id'], ['fotos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('foto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foto_id'], ['fotos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fotos_usuarios')
    op.drop_table('compras')
    with op.batch_alter_table('imagens_evento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imagens_evento_timestamp'))

    op.drop_table('imagens_evento')
    with op.batch_alter_table('fotos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fotos_timestamp'))

    op.drop_table('fotos')
    op.drop_table('usuarios')
    op.drop_table('eventos')
    # ### end Alembic commands ###
