"""tirando descricao e local

Revision ID: 4baffa3c1169
Revises: 07bce8c14651
Create Date: 2024-05-27 18:48:09.197912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4baffa3c1169'
down_revision = '07bce8c14651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('cpf')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('cpf', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
