"""tirando o hash

Revision ID: 5ad86754c876
Revises: 5b1e8adb5e11
Create Date: 2024-04-16 00:01:53.810934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad86754c876'
down_revision = '5b1e8adb5e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.String(length=128), nullable=False))
        batch_op.drop_column('senha_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('senha')

    # ### end Alembic commands ###
