"""Adiciona coluna foto_capa

Revision ID: 5b1e8adb5e11
Revises: 7d1e22337eb0
Create Date: 2024-04-05 16:00:58.448431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1e8adb5e11'
down_revision = '7d1e22337eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fotos_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('caminho_foto', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fotos_evento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fotos_evento_timestamp'), ['timestamp'], unique=False)

    op.drop_table('fotos')
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_capa', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('foto_capa')

    op.create_table('fotos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('evento_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('caminho_foto', sa.VARCHAR(length=120), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fotos_evento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fotos_evento_timestamp'))

    op.drop_table('fotos_evento')
    # ### end Alembic commands ###
