"""Adiciona a tabela FotosGaleria

Revision ID: 9ca3cae6a886
Revises: 4baffa3c1169
Create Date: 2024-05-31 22:39:55.468779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca3cae6a886'
down_revision = '4baffa3c1169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fotos_galeria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('caminho_imagem', sa.String(length=255), nullable=False),
    sa.Column('data_adicao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fotos_galeria')
    # ### end Alembic commands ###
