"""Adiciona relacionamento entre FotosGaleria e Evento

Revision ID: b35249c8d6f2
Revises: 9ca3cae6a886
Create Date: 2024-06-01 13:09:16.699129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35249c8d6f2'
down_revision = '9ca3cae6a886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotos_galeria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evento_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'eventos', ['evento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotos_galeria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('evento_id')

    # ### end Alembic commands ###
